import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>행신침례교회 | 고양시 덕양구 교회</title>
            <meta name="description" content="행신교회는 따뜻한 공동체입니다. 예배·모임 안내, 오시는 길, 섬기는 분들을 확인하세요."/>
            <meta property="og:title" content="행신침례교회"/>
            <meta property="og:description" content="예배·모임 안내, 오시는 길, 따뜻한 교회 공동체"/>
            {/*<meta property="og:image" content="/images/hero.jpg"/>*/}
            {/*<meta property="og:url" content="https://haengsin-church.site"/>*/}
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        </body>
        </html>
    );
}
